### PR TITLE
Demo midi in and out

### PR DESCRIPTION
**Pull request by mitxela**
Hi, fantastic work on all of this so far, awesome stuff.

Here is a very small contribution, to demo midi in and out. MIDI out plays a square wave on a piezo buzzer connected to pins C0 and C1. MIDI in is sent when buttons connected to C2, C3, C4 and C5 are pressed.

### CODE REVIEW

**Comment by cnlohr** [comment]
Thank you so much for your work.  Can you make a video of it working?

**Comment by cnlohr** [comment]
Does this work in Windows?

**Comment by cnlohr** [comment]
Oh wow! I just saw your video and hackaday article!  Very cool!

**Comment by mitxela** [comment]
Cheers, yes I briefly tested it on windows and it seems to work OK.

**Pull request merged**
